In [2]:
import numpy as np

In [4]:
arr1 = np.arange(6,12).reshape(3,2)

In [6]:
arr1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [10]:
arr1.ndim

2

In [14]:
arr1.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [16]:
arr1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [18]:
arr1.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [20]:
arr2 = np.arange(6,12).reshape(2,3)

In [22]:
arr3 = np.arange(12,18).reshape(2,3)

In [24]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
arr3

array([[12, 13, 14],
       [15, 16, 17]])

In [28]:
np.hstack((arr2,arr3))

array([[ 6,  7,  8, 12, 13, 14],
       [ 9, 10, 11, 15, 16, 17]])

In [30]:
np.vstack((arr2,arr3))

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [48]:
np.hsplit(arr3,3)

[array([[12],
        [15]]),
 array([[13],
        [16]]),
 array([[14],
        [17]])]

In [50]:
np.vsplit(arr3,2)

[array([[12, 13, 14]]), array([[15, 16, 17]])]

In [54]:
arr4 = np.arange(24).reshape(6,4)

arr4

Fancy Indexing

In [59]:
arr4[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

Indexing With boolean Arrays

In [66]:
arr5 = np.random.randint(low=1,high=100,size=20).reshape(4,5)

In [68]:
arr5

array([[17, 19, 34, 65, 28],
       [36, 86, 50, 14, 22],
       [36, 41, 60, 66, 33],
       [ 5, 45, 97, 13,  5]])

In [70]:
arr5 > 50

array([[False, False, False,  True, False],
       [False,  True, False, False, False],
       [False, False,  True,  True, False],
       [False, False,  True, False, False]])

In [80]:
arr5[arr5 > 50]

array([65, 86, 60, 66, 97])

In [82]:
arr5[(arr5 > 50) & (arr5 % 2 !=0)]

array([65, 97])

In [84]:
arr5[(arr5 > 50) & (arr5 % 2 !=0)]=0

In [86]:
arr5

array([[17, 19, 34,  0, 28],
       [36, 86, 50, 14, 22],
       [36, 41, 60, 66, 33],
       [ 5, 45,  0, 13,  5]])