In [2]:
import numpy as np

In [8]:
arr1 = np.arange(9).reshape(3,3)

In [10]:
arr2 = np.arange(3).reshape(1,3)

In [14]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr2

array([[0, 1, 2]])

In [18]:
arr1 + arr2

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [22]:
arr3 = np.arange(4).reshape(4,1)

In [24]:
arr3

array([[0],
       [1],
       [2],
       [3]])

In [26]:
arr4 = np.arange(12).reshape(4,3)

In [28]:
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
arr3+arr4

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [32]:
 arr5 = np.arange(4).reshape(1,4)

In [34]:
arr5

array([[0, 1, 2, 3]])

In [40]:
arr3+arr5

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])