In [2]:
import numpy as np

In [4]:
np.random.random()

0.3012982107199057

In [18]:
np.random.seed(1) #gives the same random value repetedly
np.random.random()

0.417022004702574

In [44]:
np.random.uniform(1,100) #gives random values within a range

68.83673053927919

In [46]:
np.random.uniform(1,100,10)

array([21.24077272, 87.9336262 ,  3.71137173, 67.37628351, 42.31317543,
       56.31029302, 14.89830692, 20.61204742, 80.2737123 , 96.857896  ])

In [52]:
np.random.uniform(1,100,10).reshape(2,5)

array([[28.76395521, 79.13865352, 11.21937465, 45.34145909, 90.95095481],
       [30.06780069, 29.48975852, 13.87282864,  2.91732883, 68.20471776]])

In [59]:
np.random.randint(1,10)

3

In [76]:
np.random.randint(1,20,15).reshape(3,5)

array([[ 1, 19, 11,  9, 14],
       [ 4,  1,  9, 14, 19],
       [16, 10,  1, 13, 18]])

In [90]:
a = np.random.randint(1,10,6)

In [92]:
a

array([4, 4, 9, 4, 6, 7])

In [94]:
np.max(a)

9

In [96]:
np.min(a)

4

In [112]:
np.argmax(a) #providing the index of the elements

0

In [114]:
np.argmin(a)

4

In [116]:
a = np.random.randint(1,10,5)

In [118]:
np.average(a)

4.4

In [122]:
 a[np.argmax(a)]

9

In [124]:
a[np.argmin(a)]

2

In [126]:
a = np.random.randint(1,10,6)

In [128]:
a

array([1, 5, 2, 8, 4, 2])

In [146]:
a[a%2==1] = -1 #If we want to implement conditions in an array and replace one element with another

In [148]:
a

array([-1, -1,  2,  8,  4,  2])

In [152]:
a[(a%2==0) & (a > 2)] = -2

In [186]:
b = np.random.randint(1,10,5)

In [188]:
b

array([9, 1, 7, 8, 6])

In [192]:
np.where(b%2==1,-2,b) #(condition,true,false)

array([-2, -2, -2,  8,  6])

In [195]:
c = np.arange(15).reshape(5,3)

In [198]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [200]:
np.where(c%2==0,-1,c)

array([[-1,  1, -1],
       [ 3, -1,  5],
       [-1,  7, -1],
       [ 9, -1, 11],
       [-1, 13, -1]])

In [208]:
d = np.random.randint(1,50,10)

In [210]:
d

array([27, 13,  8, 24, 40, 44, 13, 39, 28, 49])

In [212]:
np.sort(d)

array([ 8, 13, 13, 24, 27, 28, 39, 40, 44, 49])

In [224]:
 #which means the following sorted number arrays single number will be considered as a percent.So the 
#min number to max number will be considered as                        
np.percentile(d,99) 

SyntaxError: unterminated string literal (detected at line 1) (538338124.py, line 1)