In [2]:
import numpy as np

In [4]:
a = np.arange(20)

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
a = np.arange(20).reshape(5,4)

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
a[2]

array([ 8,  9, 10, 11])

In [18]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
a[:,2]

array([ 2,  6, 10, 14, 18])

In [30]:
a[:,3]

array([ 3,  7, 11, 15, 19])

In [40]:
a[:,0:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [42]:
a[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [46]:
a[3:5,2:4]

array([[14, 15],
       [18, 19]])

In [50]:
a[0]

array([0, 1, 2, 3])

In [52]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [64]:
a = np.arange(24).reshape(6,4)

In [66]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [70]:
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [72]:
 arr1 = np.array([1,2,3,4,5,6])

In [74]:
arr2 = np.array([4,5,6,7,8,9])

In [76]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [78]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [80]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [82]:
arr1 > 3

array([False, False, False,  True,  True,  True])

In [90]:
arr3 = np.arange(6).reshape(2,3)


In [92]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [100]:
arr4 = np.arange(6,12).reshape(3,2)

In [102]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [104]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [106]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [108]:
arr4.max()

11

In [110]:
 arr4.min()

6

In [112]:
arr4.max(axis = 0)

array([10, 11])

In [114]:
arr4.min(axis= 0)

array([6, 7])

In [116]:
arr4.max(axis = 1)

array([ 7,  9, 11])

In [120]:
 arr4.sum()

51

In [122]:
arr4.sum(axis = 0)

array([24, 27])

In [124]:
arr4.sum(axis = 1)

array([13, 17, 21])

In [126]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [128]:
arr4.mean()

8.5

In [130]:
arr4.mean(axis= 0)

array([8., 9.])

In [132]:
arr4.mean(axis = 1)

array([ 6.5,  8.5, 10.5])

In [134]:
arr4.std()

1.707825127659933

In [136]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [138]:
np.median(arr4)

8.5

In [140]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])