In [2]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4])

In [6]:
arr1

array([1, 2, 3, 4])

In [8]:
type(arr1)

numpy.ndarray

In [10]:
arr2 = np.array([[2,4,6,8],[1,3,5,7]])

In [12]:
arr2

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [14]:
type(arr2)

numpy.ndarray

In [16]:
arr3 = np.zeros((2,3))

In [18]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr4 = np.ones((2,3))

In [22]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr5 = np.identity(5)

In [26]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
arr6 = np.arange(10)

In [32]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr6 = np.arange(5,25,2)

In [36]:
arr6

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [38]:
arr7 = np.linspace(5,15,5)

In [40]:
arr7

array([ 5. ,  7.5, 10. , 12.5, 15. ])

In [42]:
arr7 = np.linspace(10,20,10)

In [44]:
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [46]:
arr7 = np.linspace(5,10,10)

In [48]:
arr7

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [50]:
arr8 = arr7.copy()

In [52]:
arr8

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [54]:
arr1

array([1, 2, 3, 4])

In [56]:
arr1.shape

(4,)

In [58]:
arr2

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [60]:
arr2.shape

(2, 4)

In [64]:
arr9 = np.array([[[1,2],[2,3],[7,8]]])

In [66]:
arr9

array([[[1, 2],
        [2, 3],
        [7, 8]]])

In [68]:
arr9.shape

(1, 3, 2)

In [70]:
arr9.ndim

3

In [72]:
arr2.ndim

2

In [74]:
arr1

array([1, 2, 3, 4])

In [76]:
arr1.size

4

In [78]:
arr2

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [89]:
arr2.size

8

In [91]:
arr9.size

6

In [93]:
arr9.itemsize

4

In [97]:
arr9.dtype

dtype('int32')

In [99]:
arr8.dtype

dtype('float64')

In [101]:
arr9.astype('float')

array([[[1., 2.],
        [2., 3.],
        [7., 8.]]])

In [103]:
lista = range(100)

In [105]:
Array10 = np.arange(100)

In [107]:
import sys

In [109]:
print(sys.getsizeof(55)*len(lista))

2800


In [111]:
print(Array10.itemsize*Array10.size)

400


In [113]:
Array10.size

100

In [117]:
Array10.itemsize

4

Numpy Arrays are faster in comparision to list

In [132]:
import time

In [144]:
list1 = range(10000000)
list2 = range(10000000,20000000)

start_time = time.time()

c = [(list1,list2)for list1,list2 in zip(list1,list2)]
print(time.time() - start_time)



3.412799119949341


In [142]:
arr1 = np.arange(100000)
arr2 = np.arange(100000,200000)
start_time = time.time()
c = arr1 + arr2
print(time.time() - start_time)

0.005037069320678711
