Scenario 1: You’re a teacher analyzing exam scores for a class of 10 students. You need to compute statistics and adjust scores based on specific conditions.

Tasks:

1.Create a NumPy array with 10 student scores (choose your own values between 0 and 100).
2.Calculate the average score.
3.Find the highest and lowest scores.
4.Compute the 75th percentile.
5.Identify students who scored above the 75th percentile.
6.Add a 5-point bonus to even-indexed students (e.g., students at indices 1, 3, 5, etc., 0-based) with scores above 70.

In [7]:
import numpy as np

In [9]:
arr = np.random.randint(1,100,10)

In [11]:
#1
arr

array([56,  6,  1, 60,  8, 95, 79, 49, 97, 59])

In [13]:
#2
np.average(arr)

51.0

In [15]:
#3a
arr.max()


97

In [17]:
#3b
arr.min()

1

In [19]:
#4
np.percentile(arr,75)

74.25

In [21]:
#5

In [147]:
arr 

array([56,  6,  1, 60,  8, 95, 79, 49, 97, 59])

In [152]:
arr_index = np.arange(1,len(arr),2)

Problem 2: Budget Analysis for Monthly Expenses
Scenario: You’re tracking monthly expenses for a year to manage your budget. You want to analyze spending patterns.

In [156]:
#1 Create a NumPy array with 12 months of expenses (choose realistic values in dollars, e.g., 300–1000).

totalExpense = np.random.randint(300,1000,12)

In [158]:
totalExpense

array([914, 466, 418, 986, 490, 958, 401, 599, 760, 563, 833, 492])

In [160]:
#2 Calculate the total spending for the year.
np.sum(totalExpense)

7880

In [162]:
#3 Compute the average monthly spending.
np.average(totalExpense)

656.6666666666666

In [164]:
#4 Identify months where spending exceeded $500.
np.where(totalExpense > 500,'exceeded',totalExpense).reshape(12,1)

array([['exceeded'],
       ['466'],
       ['418'],
       ['exceeded'],
       ['490'],
       ['exceeded'],
       ['401'],
       ['exceeded'],
       ['exceeded'],
       ['exceeded'],
       ['exceeded'],
       ['492']], dtype='<U11')

In [166]:
#Normalize expenses to a 0–1 scale (i.e., (x - min) / (max - min)).
totalExpense.ndim

1

In [168]:
nor = (totalExpense - totalExpense.min()) / (totalExpense.max() - totalExpense.min())

In [170]:
nor

array([0.87692308, 0.11111111, 0.02905983, 1.        , 0.15213675,
       0.95213675, 0.        , 0.33846154, 0.61367521, 0.27692308,
       0.73846154, 0.15555556])

In [172]:
#6 Sort months by spending (display indices of months in ascending order of expenses).
np.sort(totalExpense)

array([401, 418, 466, 490, 492, 563, 599, 760, 833, 914, 958, 986])

Problem 3: Weather Data Analysis
Scenario: You’re analyzing daily temperatures (in Celsius) for a week to understand weather patterns.

In [175]:
#1.Create a NumPy array with 7 daily temperatures (choose values, e.g., 15–30°C).

temp = np.random.randint(15,30,7)

In [177]:
temp

array([19, 18, 19, 18, 22, 19, 16])

In [179]:
#2.Calculate the average temperature for the week.
np.average(temp)



18.714285714285715

In [181]:
#3.Find the day(s) with the highest temperature.

temp.max()

22

In [183]:
#4. Compute the standard deviation of temperatures.

std_dev = np.std(temp,ddof=1)

In [185]:
std_dev

1.7994708216848745

In [187]:
#5. Replace temperatures below 20°C with 20°C (to simulate a minimum threshold).
temp

array([19, 18, 19, 18, 22, 19, 16])

In [189]:
temp[temp < 20] = 20


In [191]:
temp

array([20, 20, 20, 20, 22, 20, 20])

In [193]:
#6 Create a new array with temperatures converted to Fahrenheit (°F = °C * 9/5 + 32).

new_temp = (temp*9/5)+32

In [195]:
new_temp

array([68. , 68. , 68. , 68. , 71.6, 68. , 68. ])

In [225]:
arr

array([56,  6,  1, 60,  8, 95, 79, 49, 97, 59])

In [227]:
arr_index = np.arange(2,len(arr),2)

In [229]:
arr_index

array([2, 4, 6, 8])

In [244]:
arr[arr_index][arr[arr_index] > 70] += 5
print("Adjusted Scores:", arr)


Adjusted Scores: [56  6  1 60  8 95 79 49 97 59]


In [238]:
arr

array([56,  6,  1, 60,  8, 95, 79, 49, 97, 59])